# Lunch and learn: Machine learning (logistic regression)

### Goals of this notebook:
Demonstrate how to:
    1. Define the problem
    2. Clean/prepare data for building a model
    3. Train the model
    4. Evaluate the model
    5. Using the model to predict outcomes based on fresh/unseen data


### TODOS
    1. Finish write up as a proper ML notebook
    2. Host program/function on django and expose as a HTTP endpoint
    3. Prepare presentation


In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### 1. Define the problem

The most important part of any ML problem is: **what puzzle(s) do we / our clients want to solve?**

In this example, since we have data on bank marketing binary classification goal, the questions I can come up with is as follows:
- what indicators (x variables) have the biggest effect on whether a user will subscribe to a bank term deposit (y variable)?
- given that we have the variables required for the model for a given user, can we predict if the client will subscribe a bank term deposit (y variable)?

### 1. Clean/prepare data for building a model

In [ ]:
### 2. Train the model
### 3. Evaluate the model
### 4. Using the model to predict outcomes based on fresh/unseen data

In [ ]:
### 2. ingest data

In [3]:
df = pd.read_csv('./data/bank-marketing-data/bank-additional-full.csv', sep=';')

### 2.1 Understand the data
The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).

Data Sources: Sérgio Moro (ISCTE-IUL), Paulo Cortez (Univ. Minho) and Paulo Rita (ISCTE-IUL) @ 2014
   
  S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems (2014), doi:10.1016/j.dss.2014.03.001.
 
5. Number of Instances: 41188 for bank-additional-full.csv

6. Number of Attributes: 20 + output attribute.

7. Attribute information:

   ## Input variables:
   ### bank client data:
   
   1 - age (numeric)
   2 - job : type of job (categorical: "admin.","blue-collar","entrepreneur","housemaid","management","retired","self-employed","services","student","technician","unemployed","unknown")
   3 - marital : marital status (categorical: "divorced","married","single","unknown"; note: "divorced" means divorced or widowed)
   4 - education (categorical: "basic.4y","basic.6y","basic.9y","high.school","illiterate","professional.course","university.degree","unknown")
   5 - default: has credit in default? (categorical: "no","yes","unknown")
   6 - housing: has housing loan? (categorical: "no","yes","unknown")
   7 - loan: has personal loan? (categorical: "no","yes","unknown")
   ### related with the last contact of the current campaign:
   
   8 - contact: contact communication type (categorical: "cellular","telephone") 
   9 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")
  10 - day_of_week: last contact day of the week (categorical: "mon","tue","wed","thu","fri")
  11 - duration: last contact duration, in seconds (numeric). Important note:  this attribute highly affects the output target (e.g., if duration=0 then y="no"). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
  
   ### other attributes:
  12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
  13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
  14 - previous: number of contacts performed before this campaign and for this client (numeric)
  15 - poutcome: outcome of the previous marketing campaign (categorical: "failure","nonexistent","success")
  
   ### social and economic context attributes
  16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)
  17 - cons.price.idx: consumer price index - monthly indicator (numeric)     
  18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)     
  19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
  20 - nr.employed: number of employees - quarterly indicator (numeric)

  # Output variable (desired target):
  21 - y - has the client subscribed a term deposit? (binary: "yes","no")

8. Missing Attribute Values: There are several missing values in some categorical attributes, all coded with the "unknown" label. These missing values can be treated as a possible class label or using deletion or imputation techniques. 


In [21]:
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon ...         1    999         0  nonexistent          1.1   
1   may         mon ...         1    999         0  nonexistent          1.1   
2   may         mon ...         1    999         0  nonexistent          1.1   
3   may         mon ...         1    999         0  nonexistent          1.1   
4   may         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [20]:
df.describe()

age      duration      campaign         pdays      previous  \
count  41188.00000  41188.000000  41188.000000  41188.000000  41188.000000   
mean      40.02406    258.285010      2.567593    962.475454      0.172963   
std       10.42125    259.279249      2.770014    186.910907      0.494901   
min       17.00000      0.000000      1.000000      0.000000      0.000000   
25%       32.00000    102.000000      1.000000    999.000000      0.000000   
50%       38.00000    180.000000      2.000000    999.000000      0.000000   
75%       47.00000    319.000000      3.000000    999.000000      0.000000   
max       98.00000   4918.000000     56.000000    999.000000      7.000000   

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed  
count  41188.000000    41188.000000   41188.000000  41188.000000  41188.000000  
mean       0.081886       93.575664     -40.502600      3.621291   5167.035911  
std        1.570960        0.578840       4.628198      1.734447     72.251528  
min       -3.400000       92.201000     -50.800000      0.634000   4963.600000  
25%       -1.800000       93.075000     -42.700000      1.344000   5099.100000  
50%        1.100000       93.749000     -41.800000      4.857000   5191.000000  
75%        1.400000       93.994000     -36.400000      4.961000   5228.100000  
max        1.400000       94.767000     -26.900000      5.045000   5228.100000

In [ ]:
### 3. data cleaning/wrangling

In [4]:
# Treating missing values

# fastest way: dropna
df = df[df['loan'] != 'unknown']

In [5]:
df = df[df['default'] != 'unknown']

In [6]:
df = df[df['education'] != 'unknown']

In [7]:
df = df[df['job'] != 'unknown']

In [8]:
df = df[df['marital'] != 'unknown']

In [9]:
### 4. EDA
df.describe()

age      duration      campaign         pdays      previous  \
count  30488.000000  30488.000000  30488.000000  30488.000000  30488.000000   
mean      39.030012    259.484092      2.521451    956.332295      0.194273   
std       10.333529    261.714262      2.720150    201.373292      0.522788   
min       17.000000      0.000000      1.000000      0.000000      0.000000   
25%       31.000000    103.000000      1.000000    999.000000      0.000000   
50%       37.000000    181.000000      2.000000    999.000000      0.000000   
75%       45.000000    321.000000      3.000000    999.000000      0.000000   
max       95.000000   4918.000000     43.000000    999.000000      7.000000   

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed  
count  30488.000000    30488.000000   30488.000000  30488.000000  30488.000000  
mean      -0.071510       93.523311     -40.602263      3.459938   5160.813409  
std        1.610399        0.585374       4.789249      1.777231     75.158065  
min       -3.400000       92.201000     -50.800000      0.634000   4963.600000  
25%       -1.800000       93.075000     -42.700000      1.313000   5099.100000  
50%        1.100000       93.444000     -41.800000      4.856000   5191.000000  
75%        1.400000       93.994000     -36.400000      4.961000   5228.100000  
max        1.400000       94.767000     -26.900000      5.045000   5228.100000

In [10]:
# Convert string data to numerical data so that scikitlearn can understand it
cols_to_transform = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week',
                    'poutcome', 'y']
df_with_dummies = pd.get_dummies(df, columns = cols_to_transform)

In [11]:
df_with_dummies.head()

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   56       261         1    999         0           1.1          93.994   
2   37       226         1    999         0           1.1          93.994   
3   40       151         1    999         0           1.1          93.994   
4   56       307         1    999         0           1.1          93.994   
6   59       139         1    999         0           1.1          93.994   

   cons.conf.idx  euribor3m  nr.employed  ...    day_of_week_fri  \
0          -36.4      4.857       5191.0  ...                  0   
2          -36.4      4.857       5191.0  ...                  0   
3          -36.4      4.857       5191.0  ...                  0   
4          -36.4      4.857       5191.0  ...                  0   
6          -36.4      4.857       5191.0  ...                  0   

   day_of_week_mon  day_of_week_thu  day_of_week_tue  day_of_week_wed  \
0                1                0                0                0   
2                1                0                0                0   
3                1                0                0                0   
4                1                0                0                0   
6                1                0                0                0   

   poutcome_failure  poutcome_nonexistent  poutcome_success  y_no  y_yes  
0                 0                     1                 0     1      0  
2                 0                     1                 0     1      0  
3                 0                     1                 0     1      0  
4                 0                     1                 0     1      0  
6                 0                     1                 0     1      0  

[5 rows x 59 columns]

In [12]:
# Preparing the data into 2 sets: X and y variables

df_y = df_with_dummies[['y_yes']]
df_y.head()

y_yes
0      0
2      0
3      0
4      0
6      0

In [13]:
del df_with_dummies['y_yes']
del df_with_dummies['y_no']
df_with_dummies.head()

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   56       261         1    999         0           1.1          93.994   
2   37       226         1    999         0           1.1          93.994   
3   40       151         1    999         0           1.1          93.994   
4   56       307         1    999         0           1.1          93.994   
6   59       139         1    999         0           1.1          93.994   

   cons.conf.idx  euribor3m  nr.employed        ...         month_oct  \
0          -36.4      4.857       5191.0        ...                 0   
2          -36.4      4.857       5191.0        ...                 0   
3          -36.4      4.857       5191.0        ...                 0   
4          -36.4      4.857       5191.0        ...                 0   
6          -36.4      4.857       5191.0        ...                 0   

   month_sep  day_of_week_fri  day_of_week_mon  day_of_week_thu  \
0          0                0                1                0   
2          0                0                1                0   
3          0                0                1                0   
4          0                0                1                0   
6          0                0                1                0   

   day_of_week_tue  day_of_week_wed  poutcome_failure  poutcome_nonexistent  \
0                0                0                 0                     1   
2                0                0                 0                     1   
3                0                0                 0                     1   
4                0                0                 0                     1   
6                0                0                 0                     1   

   poutcome_success  
0                 0  
2                 0  
3                 0  
4                 0  
6                 0  

[5 rows x 57 columns]

In [14]:
df_with_dummies.as_matrix()

array([[  56.,  261.,    1., ...,    0.,    1.,    0.],
       [  37.,  226.,    1., ...,    0.,    1.,    0.],
       [  40.,  151.,    1., ...,    0.,    1.,    0.],
       ..., 
       [  56.,  189.,    2., ...,    0.,    1.,    0.],
       [  44.,  442.,    1., ...,    0.,    1.,    0.],
       [  74.,  239.,    3., ...,    1.,    0.,    0.]])

In [15]:
# convert pandas dataframe into numpy array
from numpy import array
X = df_with_dummies.as_matrix()
y = df_y.as_matrix() # this step may not be necessary

In [ ]:
### 5. Train the model

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [18]:
logisticregression = LogisticRegression().fit(X_train, y_train)
print("training set score: %f" % logisticregression.score(X_train, y_train))
print("test set score: %f" % logisticregression.score(X_test, y_test))

/Users/davidtan/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


training set score: 0.900245
test set score: 0.899370


In [19]:
from sklearn import metrics

In [22]:
expected = y_test
predicted = logisticregression.predict(X_test)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))

             precision    recall  f1-score   support

          0       0.92      0.97      0.94      6662
          1       0.66      0.42      0.51       960

avg / total       0.89      0.90      0.89      7622



In [23]:
print(metrics.confusion_matrix(expected, predicted))

[[6455  207]
 [ 560  400]]


In [40]:
# Using our trained model to predict whether y will be 1 or 0

sample_input = X_test[0]

# Using .predict_proba() .predict_proba() returns the probability of the sample for each class in the model, where classes are ordered as 
# they are in self.classes_.
print(logisticregression.predict_proba(sample_input))


# Using .predict()  This returns the class label (i.e. whether the prediction is 0 or 1)
print(logisticregression.predict(sample_input))


[[ 0.90609139  0.09390861]]
[0]


/Users/davidtan/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/davidtan/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [41]:
# Using our trained model to predict whether y will be 1 or 0

sample_input_2 = X_test[2]

# Using .predict_proba() .predict_proba() returns the probability of the sample for each class in the model, where classes are ordered as 
# they are in self.classes_.
print(logisticregression.predict_proba(sample_input_2))


# Using .predict()  This returns the class label (i.e. whether the prediction is 0 or 1)
print(logisticregression.predict(sample_input_2))


[[ 0.24718234  0.75281766]]
[1]


/Users/davidtan/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/davidtan/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1], dtype=uint8)

In [42]:
from sklearn.linear_model import LogisticRegressionCV

In [44]:
logisticregressionCV = LogisticRegressionCV().fit(X_train, y_train)
print("training set score: %f" % logisticregressionCV.score(X_train, y_train))
print("test set score: %f" % logisticregressionCV.score(X_test, y_test))

training set score: 0.900245
test set score: 0.900026


In [46]:
logisticregression.C

1.0

In [49]:
logisticregression.solver

'liblinear'

In [48]:
logisticregressionCV.

'lbfgs'